name: build-docker-image
run-name: ${{ github.actor }} - ${{ github.event_name }}
on: [push]
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'
      - name: Setup and install dependencies
        working-directory: ./lb-recipes-backend-src
        run: |
          corepack enable pnpm
          pnpm install --frozen-lockfile --prod
      - name: Check versions
        run: |
          VERSION_FILE_PATH="lb-recipes-backend-src/src/config/version.ts"
          TF_VERSION_FILE_PATH="lb-recipes-backend-infr/container_image.tf"
          CURR_VERSION=$(cat $VERSION_FILE_PATH | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')
          CURR_TF_VERSION=$(cat $TF_VERSION_FILE_PATH | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')
          if [ "$CURR_VERSION" != "$CURR_TF_VERSION" ]; then
            printf "💥 Terraform & JS versions are not equal. Exiting"
            exit 1
          fi
      - name: Build and push Docker image
        run: |
          VERSION_FILE_PATH="lb-recipes-backend-src/src/config/version.ts"
          CURR_VERSION=$(cat $VERSION_FILE_PATH | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')
          cd lb-recipes-backend-src
          docker build -t "lb-recipes-backend:v$CURR_VERSION" .
          echo done
