name: Build and Push to Artifact Registry
run-name: ${{ github.actor }} - ${{ github.event_name }}
on:
  push:
    branches: ["main", "feat/docker-build"]
  pull_request:
    branches: ["main"]
jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Brach name
        run: echo ${{ github.ref }}

      - name: Checkout branch
        run: git checkout ${{ github.ref }}

      - name: "Version bump"
        run: |
          git branch --show-current
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          ./automatic-version-bump.sh

      

      # - id: "auth"
      #     uses: "google-github-actions/auth@v1"
      #     with:
      #       credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      # - name: "Set up Cloud SDK"
      #   uses: "google-github-actions/setup-gcloud@v1"

      # - name: "Use gcloud CLI"
      #   run: "gcloud info"

      # - name: "Docker auth"
      #   run: |-
      #     gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      # - name: Build image
      #   run: docker build . --file DOCKERFILE_LOCATION --tag ${{ env.GAR_LOCATION }}
      #   working-directory: WORKING_DIRECTORY

      # - name: Push image
      #   run: docker push ${{ env.GAR_LOCATION }}